### ISSUE TITLE
Quick question about three drivers

### ISSUE THREAD

**Issue by javl** [dwinters42/PiZero-GRBL-Hat#1]
Just a quick question: did you use two stepper drivers just because you only needed /could fit two of them? Just wondering before I adapt your design to fit one for the z-axis as well and it turns out to be some hardware limitation I've missed ;)

**Comment by dwinters42** [comment]
Hi Jasper,

> Just a quick question: did you use two stepper drivers just because you only needed /could fit two of them? Just wondering before I adapt your design to fit one for the z-axis as well and it turns out to be some hardware limitation ;)
> 
The reason that the board has only 2 stepper drivers is that I only needed 2 for a 2-axis gimbal I wanted to drive. GRBL on the ATmega328p supports 3 stepper, so no reason not to add a 3rd driver...

Let me know if you decide to design a 3-axis version!

Cheers,
Daniel

**Comment by javl** [comment]
Thanks, I will. And thank you for putting all of the KiCad files online.
